language: android
dist: trusty

android:
    components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_pla_services
    - sys-img-x86-android-28
    
before_install:
  - echo y | sdkmanager "ndk-bundle"
  - sudo apt install npm
  - npm install
  - cd android
  - chmod +x gradlew